version: '3'
services:
  database:
    container_name: postgres-comp2020
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - C:/Users/user/Desktop/FULLSTACK/csc2020:/data/postgres
    env_file:
    - comp2020.env
    extra_hosts:
      - "app-server: 192.168.43.1"

  web:
    container_name: nginx-csc2020
    build:
      context: .
      dockerfile: nginx-primer/Dockerfile
    ports:
     - 8080:80
     - 443:443