version: '3'
services:
  database:
    container_name: postgres-comp2020
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - C:/Users/user/Desktop/FULLSTACK/csc2020:/data/postgres
    env_file:
    - comp2020.env